spring.application.name=service-rental
server.port=8282

## MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/RentalServiceDb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##########
jwt.secret=yourSecretKeyHere
